title: "RustBridge"
description: "An inclusive workshop program for newcomers to Rust"
#theme: just-the-docs
plugins:
  - jekyll-octicons
markdown: "kramdown"
kramdown:
  parse_block_html: true
permalink: pretty
search_enabled: true
aux_links:
  "Edit this on GitHub":
    - "https://github.com/rustbridge/website"
sass:
  style: :compressed

links:
  contact:
    Twitter: "https://twitter.com/rustbridge"
    Discord: "https://discord.gg/jEKp4bXC"
    GitHub: "https://github.com/rustbridge/"
  resources:
    "Rust": "https://www.rust-lang.org/"
    Rustlings: "https://github.com/rust-lang/rustlings"
    "Rusty Snake Book": "https://snake.rustbridge.com/"

collections:
  - lesson_plans
